# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
#recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
#assistant_id: placeholder_default

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es


#  Configuraci贸n del pipeline de procesamiento del lenguaje natural (NLU)
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: null
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

#  Configuraci贸n de pol铆ticas para manejar la conversaci贸n
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: RulePolicy
  core_fallback_action_name: "action_fallback_ia"
  core_fallback_threshold: 0.3
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
  

#  Configuraci贸n de la sesi贸n del chatbot
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
assistant_id: 20250302-174702-pleasant-dictionary

